### ISSUE TITLE
Allow CLI usage

### ISSUE THREAD

**Issue by TheBB** [TGS963/upscayl#10]
E.g. `upscayl --general *.jpg`

**Comment by NayamAmarshe** [comment]
You can download the upscayl binary from resources folder. It's taken from Real-ESRGAN-ncnn-vulkan and use the terminal to upscale images.

**Comment by infinity0** [comment]
Upscayl in fact does have an internal CLI, which you can see, together with its CLI args, in the stdout logs it outputs when processing an image. On GNU/Linux this is located at `/opt/Upscayl/resources/bin/upscayl-bin`. It even takes `--help` so you can see what all the options are.

**Comment by aaronliu0130** [comment]
That's what Nayam said before his account got banned and every action in issues he did was expunged from the records. As you can see, issue histories are now wildly confusing.

Also, the repository of our CLI is linked in the README.

**Comment by N0rdmann** [comment]
**So there will never be an option for the GUI to simply start it upscayl %1 with a picture pre-loaded?** 🤔

_Use-case:_ Just wanted to call it for certain images from my image browser then having preview functions and UI stuff to decide how to upscale it
