### ISSUE TITLE
Error at startup (nss_util.cc(349))  with the AppImage version 1.1.1

### ISSUE THREAD

**Issue by sebsauvage** [TGS963/upscayl#26]
Error when starting the application:
```
$./Upscayl-1.1.1.AppImage 
ICON:  /tmp/.mount_Upscaya0Izla/resources/app.asar/main/icon.png
Checking for update
[38219:0825/132207.974222:ERROR:nss_util.cc(349)] After loading Root Certs, loaded==false: NSS error code: -8018
Update for version 1.1.1 is not available (latest version: 1.1.1, downgrade is disallowed).
```

Operting system is:
```
$inxi -S
System:    Host: xxxxxxxxxx Kernel: 5.4.0-125-generic x86_64 bits: 64 Desktop: MATE 1.24.0 
           Distro: Ubuntu 20.04.4 LTS (Focal Fossa)
```
(machine name masked)
Computer is properly connected to the internet.

This only occurs with the AppImage package. The Flatpak versions works.

**Comment by NayamAmarshe** [comment]
Your system is missing libnss and other libraries. You also are running an outdated kernel.

Please read:
https://askubuntu.com/questions/987406/error-initializing-nss-when-trying-to-launch-google-chrome
