### ISSUE TITLE
upscayl not "Free and Open Source"

### ISSUE THREAD

**Issue by LouisNitag** [TGS963/upscayl#27]
Upscayle is described in its Readme as a "Free and Open Source AI Image Upscaler".

But only the user interface is open source. The software relies on the binary [upscayl](https://github.com/TGS963/upscayl/blob/main/resources/linux/bin/upscayl) to work properly, without providing sources for this binary.

Thus the software is not "Free and Open Source" as some parts are closed-sources.

- Solution 1: release the code to build the `upscayl` binary and share it under a "Free and Open Source" license
- Solution 2: remove the mention "Free and Open Source" from the Readme.

**Comment by NayamAmarshe** [comment]
The source to the binary is already mentioned in the credits. If you would like more free options, you're free to compile your own from Real-ESRGAN's repository.

**Comment by M1cha** [comment]
@NayamAmarshe this could easily be solved by using github actions. With that you can automate building that binary so everybody can see how it's done and you can remove the precompiled binary from the repo.
